### ISSUE TITLE
Problems with grouped convolutions

### ISSUE THREAD

**Issue by aradar** [google-research/morph-net#101]
Hi,

I am currently trying to shrink a segmentation model which uses grouped convolutions with the `GammaFlopsRegularizer`. The grouped convolutions are implemented as follows:

```
            +-----------+
            | op: split |
            +-----------+
                  |
       +----------------------+
       |                      |
+------------+         +------------+
| op: conv2d |   ...   | op: conv2d | 
+------------+         +------------+
       |                      |
       +----------------------+
                  |
            +------------+
            | op: concat |
            +------------+
                  |
          +---------------+
          | op: batchnorm |
          +---------------+
```

Using morph-net on a model which contains such layers/ structures causes an endless loop during regularizer generation. The loop seems to be caused by the split operation which expands the group rather than closing it (which makes totally sense usually). 

My current workaround is adding the Split operation as a `OutputNonPassthroughOpHandler` in the `_get_base_op_handler_dicts()` function of the `framework/op_handlers.py` module. This seems to stop the endless loop but I am not sure it this produces the correct regularizer groups.

As this "workaround" seems rather hacky and potentially breaks the grouping for other structures, I am curious if you see a better way to solve this problem?

Thank you for your help and your awesome framework!

**Comment by aradar** [comment]
After debugging the regularizer grouping code I found the reason for the looping. It is caused by the combination of the following facts:

- The `GroupingOpHandler` adds new input and output ops with different shapes than the current one to the queue 
- `tf.split()` returns a Split op and not a SplitV op if a scalar is used as `num_or_size_splits` param
- `OP_TYPES_WITH_MULTIPLE_OUTPUTS` in the `op_handler_util.py` module contains only "SplitV" 
- Because of the missing entry in `OP_TYPES_WITH_MULTIPLE_OUTPUTS` `get_op_size()` returns the shape of the first output for the Split op which has obviously not the same shape as the input tensors which got split by the op

My fix for this is now to add "Split" to the `OP_TYPES_WITH_MULTIPLE_OUTPUTS` variable of the `op_handler_util.py` module and I think this is a general fix for the problem and maybe also prevents loops in other situations.

**Comment by eladeban** [comment]
Thanks for pointing this out.

What you suggest with adding split to `OP_TYPES_WITH_MULTIPLE_OUTPUTS` could work in the sense that it wont crash. If you uniformly use grouped convolutions in your network with the same number of groups, I think it will even do the right thing. But I think this will not use the correct number of inputs to the convolutions, specifically it will use the number of channels before the split.

A work around could be to use the supported (yet to the best of my knowledge, undocumented) [feature](https://github.com/tensorflow/tensorflow/pull/25818) of `tf.nn.conv2d`.
Basically if you feed a weight matrix of appropriate size it will performe a grouped convolution, see:
```
inputs = tf.zeros([3, 10, 10, 64], name='my_input')
groups = 4
filter_per_group = 1
kernel = tf.zeros([1, 1, 64 / groups, groups * filter_per_group], name='my_kernel')
out = tf.nn.conv2d(inputs, kernel, padding='VALID')
print out.shape
```
this solution is not perfect as the exporter structure could have as number of outputs a number which is not a multiply of by the number of groups. 

The correct way to handle this is to modify the conv2d op handler, and also write a handler for tf.split. We will keep you posted when we get to that.

**Comment by aradar** [comment]
Thank you for your response!

I'am currently running the training of three "morphed" variants of my model which now use the new undocumented group convolutions instead of my own implementation based on the split operation. Which shows that this workaround works as intended. 

My current solution to get around the problem with the number of channels being a multiple of the number of groups is, that I scale the number of channels to to nearest bigger multiple of the number of groups.

I may find time in the next few days to look into implementing the needed changes myself. So if you are interested I can make a pull request if I get it to work.

**Comment by eladeban** [comment]
@aradar ,  will be happy to see your solution  for this!
Closing for now.
