### ISSUE TITLE
Getting this Error

### ISSUE THREAD

**Issue by rythmm** [google-research/morph-net#112]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-517179d25c2f> in <module>()
      4 logits = build_model()
      5 
----> 6 network_regularizer = flop_regularizer.GammaFlopsRegularizer( output_boundary=[logits.op],
      7      gamma_threshold=1e-3)
      8 

AttributeError: 'Sequential' object has no attribute 'op'

**Comment by eladeban** [comment]
I guess you are using a keras layer so `logits` is actually **not** a `tensor` and hence it dose **not** have the attribute op.
You have to add the `flop_regularizer` somewhere that has access to the `tensor`, this would probably be after you *really* build the model something like `logits(inputs)` (maybe?)
