### ISSUE TITLE
Query on Morph Net Structure Exporter

### ISSUE THREAD

**Issue by retazo0018** [google-research/morph-net#134]
I have a Keras Sequential Model and I train the model using,
`model.fit(x_train.values, y_train.values, batch_size=1024, epochs=10, verbose=2, validation_data=(x_valid,y_valid))`
I have configured morphnet to this model. In this case, is there a way to save the model structure using structure exporter?

**Comment by eladeban** [comment]
I think that the StructureExporter should still work regardless on how you trained it.

**Comment by retazo0018** [comment]
Thank you for your reply! I will look into it.
