### ISSUE TITLE
Can morph-net output a pruned model file?

### ISSUE THREAD

**Issue by evi-Genius** [google-research/morph-net#142]
I am new to Tensorflow, and I want to konw if there is a way to output a pruned model file for future training? Now morph-net output variable name and channel number, but user must construct pruned model manaully every time after pruning

**Comment by evi-Genius** [comment]
And I guess I may use the alive_x file to construct pruned model automatically. But I don't konw how.

**Comment by eladeban** [comment]
the alive_x is the pruned model!
You need to do some simple pipeling to read the structure file and insert the sizes in your model *programmatically*. That is 
`conv2d(inputs,learned_structure[layer_name], ... name=layer_name)`

**Comment by smohan10** [comment]
It would be wonderful if you could provide a utility which uses the network.py file and can construct a graph object based on the alive_x file using TF slim example. I see an example only for training in the train_image_classifier.py which generates the alive_x files.
