### ISSUE TITLE
MorphNet not working on google colab

### ISSUE THREAD

**Issue by H-arshit** [google-research/morph-net#146]
In my experimentation when I tried to use Morph-net on google colab there were no changes in the learned-structures while when I tried to run the same code on RTX8000 it was able to optimize the network. Would Morphnet not work on google-colab or is there a restriction to the batch size for morphnet to work.

**Comment by eladeban** [comment]
there should not be any problem with a colab. Do you see a valid value for the cost and regularization strength? is it the same values you get on the RTX?
