### ISSUE TITLE
Can I use MorphNet to slim my model trained by Pytorch?

### ISSUE THREAD

**Issue by NjtechPrinceling** [google-research/morph-net#174]
Just like the title，I have a model trained by Pytorch, Can i use this project to slim it..
Eg: Convert Pytorch's model to ONNX, then read by Tensorflow?
Thanks!

**Comment by eladeban** [comment]
sorry fo the late reply, you need to do the structure learning in TensorFlow as this is a TensorFlow framework... it is not about converting the *trained* model, its about learning the structure.
Implementing the algorithm int Pytorch should not be super hard, and you are welcome to add it here..
