### ISSUE TITLE
Can I export model optimized by morph-net to tflite？

### ISSUE THREAD

**Issue by sunzhe09** [google-research/morph-net#19]

**Comment by pkch** [comment]
MorphNet only produces a set of JSON files with the proposed structure. Building the modified model that uses the discovered structure is a separate step, done outside MorphNet.

The JSON files are not specific to any particular ML framework: they just map the names of the supported ops to the output channel counts.  The names of the ops are taken from the TensorFlow graph but it should be pretty straightforward to map those op names to the equivalent concepts in other frameworks.
