### ISSUE TITLE
License discrepancy: MIT vs. Apache

### ISSUE THREAD

**Issue by mbrukman** [google-research/morph-net#24]
The [`setup.py`][setup.py] in the repo says the code is under the **MIT** license:

> ```python
> "License :: OSI Approved :: MIT License",
> ```

while the [`LICENSE`][license] file contains the **Apache 2.0** license, which is confusing. 

Could you please clarify which license this repo is under and fix one or the other file to ensure consistency?

Thanks!

[setup.py]: https://github.com/google-research/morph-net/blob/6045ba041428e941151c335ec298c27ca8d0d4c3/setup.py#L21
[license]: https://github.com/google-research/morph-net/blob/6045ba041428e941151c335ec298c27ca8d0d4c3/LICENSE

**Comment by pkch** [comment]
Thanks for catching this!
