### ISSUE TITLE
How to save the JSON file which extract the Architeture Learned by MorphNet?

### ISSUE THREAD

**Issue by XiaotianM** [google-research/morph-net#38]
Hi, thanks for open souring.  when I followed the instructions for extracting the Architecture Learned by MorphNet,  the code reported an error. 

> NotFoundError: xxxxxxx/epoch_1/learned_structure/alive_999; No such file or directory

However, when I see the code following:
```
  def create_file_and_save_alive_counts(self, train_dir: Text,
                                        global_step: tf.Tensor) -> None:
    """Creates a file and saves live counts to it.

    Creates the directory {train_dir}/learned_structure/ and saves the current
    alive counts to {path}/{_ALIVE_FILENAME}_{global_step} and overwrites
    {path}/{_ALIVE_FILENAME}.

    Args:
      train_dir: where to export the alive counts.
      global_step: current value of global step, used as a suffix in filename.
    """
    current_filename = '%s_%s' % (_ALIVE_FILENAME, global_step)
    directory = os.path.join(train_dir, 'learned_structure')
    try:
      tf.gfile.MkDir(directory)
    except tf.errors.OpError:
      # Probably already exists. If not, we'll see the error in the next line.
      pass
    with tf.gfile.Open(os.path.join(directory, current_filename), 'w') as f:
      self.save_alive_counts(f)
    with tf.gfile.Open(os.path.join(directory, _ALIVE_FILENAME), 'w') as f:
      self.save_alive_counts(f)
```

the code does not try to make file for os.path.join(directory, current_filename) and os.path.join(directory, _ALIVE_FILENAME).

Is the way I use incorrectly?

thanks for your reply

**Comment by Delysky** [comment]
`from datasets import flowers
from morph_net.network_regularizers import flop_regularizer
from morph_net.tools import structure_exporter
import pdb
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" 

# This might take a few minutes.
train_dir = '/home/ant/researchInstitute/zengdetian/code/train_logs5'
print('Will save model to %s' % train_dir)

with tf.Graph().as_default():
#     tf.logging.set_verbosity(tf.logging.INFO)

    dataset = flowers.get_split('train', '/home/ant/researchInstitute/zengdetian/code/TFRecord')
    images, _, labels = load_batch(dataset, batch_size=32)

    # 创建模型:
#     logits = my_cnn(images, num_classes=dataset.num_classes)
    logits = resnet(preprocessed_inputs = images, num_classes=dataset.num_classes)
#     logits = v4(images, num_classes=dataset.num_classes)
    # logits是否需要变为one-hot编码
    
    network_regularizer = flop_regularizer.GammaFlopsRegularizer([logits.op], gamma_threshold=1e-20)
#     pdb.set_trace()
    regularization_strength = 1e-10
    regularizer_loss = (network_regularizer.get_regularization_term() * regularization_strength)
#     print(network_regularizer.op_regularizer_manager)
#     se = structure_exporter.StructureExporter(network_regularizer.op_regularizer_manager)
    # 传入模型的标签和输出
    model_loss = tf.nn.sparse_softmax_cross_entropy_with_logits(labels=labels, logits=logits)
    optimizer = tf.train.MomentumOptimizer(learning_rate=0.01, momentum=0.9)
    total_loss1 = model_loss + regularizer_loss


    total_loss = tf.reduce_sum(total_loss1, [0])
    train_op = optimizer.minimize(model_loss + regularizer_loss)   
    train_op = slim.learning.create_train_op(total_loss, optimizer)  # tf.losses.get_losses

    # 开始训练:
    final_loss = slim.learning.train(train_op, logdir=train_dir, number_of_steps=200, # For speed, we just do 1 epoch
      save_summaries_secs=1)
    
    # 保存模型
    se = structure_exporter.StructureExporter(network_regularizer.op_regularizer_manager)
    f = open('morphnet_result', 'w')
#     pdb.set_trace()
    print(se._alive_vectors)
    se.save_alive_counts(f)`

**Comment by Delysky** [comment]
I used the code which provided in MorphNet_GTC2019.pdf to reduce resnet-50, but the result show that
![image](https://user-images.githubusercontent.com/26110605/56848947-b8189700-6920-11e9-9220-5d6f45c4d299.png)
could you show me the reason?

**Comment by Delysky** [comment]
![image](https://user-images.githubusercontent.com/26110605/56848977-15144d00-6921-11e9-9a6e-eec0f607cffc.png)

**Comment by pkch** [comment]
`StructureExporter` API requires that you call a method `populate_tensor_values` before saving the files; see https://github.com/google-research/morph-net#extracting-the-architecture-learned-by-morphnet for the example.

This API is required because `StructureExporter` is designed to support CPU, GPU, and TPU, so it cannot assume that it can create its own session to compute the values of the tensors (this would be prohibitively expensive in some cases). So the API expects the user to compute the tensor values in their own session, and provide them to the `StructureExporter` instance.

**Comment by Delysky** [comment]
great！ I have sloved the problem!

**Comment by wonderfulboy** [comment]
> great！ I have sloved the problem!

hello! the exporter._alive_vectors is empty!  could you show me the reason? thanks

**Comment by nt3m5p** [comment]
so what is  the specific op ?

**Comment by waqarahmed4544** [comment]
> great！ I have sloved the problem!

@Delysky can you please share your working code? I am still struggling to fix this issue.
