### ISSUE TITLE
How could I use flop_regularizer  on MobilnetV2 model(in tf.slim)?

### ISSUE THREAD

**Issue by 1224wxwx** [google-research/morph-net#53]
Hi,thank you very much for this awesome project!

I use morphnet on MobilnetV2 and get errors like:
"RuntimeError: OpRegularizerManager could not handle ops: [u'MobilenetV2/Logits/Dropout/dropout_1/Shape (Shape)', u'MobilenetV2/Logits/AvgPool (AvgPool)']"

How could I solve this error？

**Comment by pkch** [comment]
This seems to be the same issue as #35. Did you resolve it or it still happens on MobileNet?

**Comment by pkch** [comment]
Duplicate of #35
