### ISSUE TITLE
ValueError: Total size for op slices do not match

### ISSUE THREAD

**Issue by PeterStone007** [google-research/morph-net#54]
when I use multiple output like this

network_regularizer = flop_regularizer.GammaFlopsRegularizer([box_pred.op, cls_pred.op], gamma_threshold=1e-3)

I got this error

INFO:tensorflow:OpRegularizerManager starting analysis from: [<tf.Operation 'concat_2' type=ConcatV2>, <tf.Operation 'concat_3' type=ConcatV2>].
INFO:tensorflow:OpRegularizerManager found 3414 ops and 61 sources.
Total size for op slices do not match: %s' % op_slice_sizes)                                                                                                                 
ValueError: Total size for op slices do not match: [[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3], [3]]

I am confused so much. Thank you for reply!
the shape of outputs are:
<class 'tensorflow.python.framework.ops.Tensor'> (48, 2046, 4)
<class 'tensorflow.python.framework.ops.Tensor'> (48, 2046, 4)
@batzner @eladeban

**Comment by shishichang** [comment]
meet the same error
 it caused by:
`  # Check that all ops have the same total size.
  total_slice_sizes = [
      get_total_slice_size(op_slice_size, 0, len(op_slice_size))
      for op_slice_size in op_slice_sizes]
  if total_slice_sizes.count(total_slice_sizes[0]) != len(total_slice_sizes):
    raise ValueError(
        'Total size for op slices do not match: %s' % op_slice_sizes)`

Does anyone knows what this means ?

**Comment by eladeban** [comment]
Thanks for raising the issue. We will take a look.
Could you produce a minimal (small?) example where this happens?

**Comment by PeterStone007** [comment]
I have tried your work with detection framework ssd, the outputs are location results and classification results from multi feature maps, then concat together as cls_pred and loc_pred. The code and error as below:
 

[ 203] cls_pred = prediction_dict['class_predictions_with_background']
[ 204] loc_pred = prediction_dict['box_encodings']
[ 205] print(cls_pred)
[206 ] print(loc_pred)
[207] network_regularizer = flop_regularizer.GammaFlopsRegularizer([cls_pred.op, loc_pred.op], gamma_threshold=1e-3)
[208] regularization_strength = 1e-10
[209] regularizer_loss = (network_regularizer.get_regularization_term()*regularization_strength)

Tensor("concat_3:0", shape=(48, 2046, 4), dtype=float32, device=/device:GPU:0)
Tensor("concat_2:0", shape=(48, 2046, 4), dtype=float32, device=/device:GPU:0)
INFO:tensorflow:OpRegularizerManager starting analysis from: [<tf.Operation 'concat_3' type=ConcatV2>, <tf.Operation 'concat_2' type=ConcatV2>].
INFO:tensorflow:OpRegularizerManager found 3414 ops and 61 sources.
Traceback (most recent call last):
File "./object_detection/train_morphnet.py", line 213, in <module>
tf.app.run()
object_detection/trainer_morphnet.py", line 207, in train
network_regularizer = flop_regularizer.GammaFlopsRegularizer([cls_pred.op, loc_pred.op], gamma_threshold=1e-3)
/morph_net/network_regularizers/flop_regularizer.py", line 67, in __init__
framework/op_regularizer_manager.py", line 126, in __init__
regularizer_blacklist=regularizer_blacklist)
/morph_net/framework/op_regularizer_manager.py", line 126, in __init__
self._op_handler_dict[op.type].assign_grouping(op, self)
/morph_net/framework/concat_op_handler.py", line 61, in assign_grouping
concat_op_slices, input_op_slices, output_op_slices)
/morph_net/framework/op_handler_util.py", line 241, in get_aligned_op_slice_sizes
return get_aligned_sizes(all_op_slice_sizes)
/morph_net/framework/op_handler_util.py", line 271, in get_aligned_sizes
'Total size for op slices do not match: %s' % op_slice_sizes)
ValueError: Total size for op slices do not match: [[3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,3, 3, 3, 3, 3, 3], [3]]

**Comment by pkch** [comment]
This problem *usually* happens when the op regularizer graph traversal ends up in the part of the graph where it shouldn't. For example, the image preprocessing section of the graph cannot be optimized by MorphNet since all channel counts there are fixed (based on image size). Once the regularizer enters this part of the graph, it encounters a lot of complexity that it sometimes cannot handle correctly.

The best solution to is to prevent the op regularizer from ending up in the wrong neighborhood in the first place. For example, perhaps there's an op that separates the image input/preprocessing subgraph from the main model; marking  that op as a leaf would prevent the traversal from passing it (e.g. as in [here]( https://github.com/google-research/morph-net/blob/a01a02aea8269ee5e57dd35772ebb6b3daff0c42/morph_net/framework/op_handlers.py#L34)). For instance, maybe `DepthToSpace` is such an op, in that case you can add it to the list alongside `SpaceToDepth`. 

If there is no op that can be used so, let us know and we'll try to figure out a different approach.

**Comment by eladeban** [comment]
What I meant by "example" is more like code which shows what is the graph that led to this bug, and not what are the 3 lines of code before it crashes :)

In any case, I added #59 which should help in the debugging. I am also working on #60 which could help solve the problem. Could you try:
1. `network_regularizer = flop_regularizer.GammaFlopsRegularizer([cls_pred.op]`
2. `network_regularizer = flop_regularizer.GammaFlopsRegularizer([cls_loc.op]`
I suspect that most of the FLOPs are in the former and also I suspect that the error is in the latter (might be wrong).

If you could also paste:
```
g = tf.get_default_graph()
for op in g.get_operations():
  if not any([bad in op.name for bad in ['Assign','read','Initializer','Relu','BiasAdd']]):
    print op.name
```
it could be informative.

**Comment by eladeban** [comment]
Happy to say that concat with axis different than 3 (or -1) is correctly supported. Please do let us know if this helped.

**Comment by Chris19920210** [comment]
Hi, I also face the same issue. I wanna apply morph_net to some recommendation model which  involves GRU and attention structures. 

I got the error:
  File "/home/rihan.crh/dien/script_pruning_morph/morph_net/framework/concat_op_handler.py", line 81, in assign_grouping
    concat_op_slices, input_op_slices, output_op_slices)
  File "/home/rihan.crh/dien/script_pruning_morph/morph_net/framework/op_handler_util.py", line 269, in get_aligned_op_slice_sizes
    return get_aligned_sizes(all_op_slice_sizes)
  File "/home/rihan.crh/dien/script_pruning_morph/morph_net/framework/op_handler_util.py", line 299, in get_aligned_sizes
    'Total size for op slices do not match: %s' % op_slice_sizes)
ValueError: Total size for op slices do not match: [[1], [3]]

the coresponding op:
type: ConcatV2
name: rnn_1/gru1/concat_1

And I add the bn structure after the dynamic_rnn structure with gru cells.

Can anyone help? thanks
