### ISSUE TITLE
Does morph-net have an operation to build a new model with it's FLOP/Latency optimized outputs?

### ISSUE THREAD

**Issue by athorneak13** [google-research/morph-net#76]
Just wanted to confirm. Once we have trained our initial model we have a json file containing the optimized output sizes of the different layers. When I want to retrain a new model with these newly optimized output sizes I have to create a new model from scratch with these newly optimized output sizes, correct? I've been looking through the documentation to see if there is some kind of function that will do it for us, but haven't been able to find anything.

**Comment by eladeban** [comment]
In a nutshell instead of having in your code
```
net = conv2d(inputs, 64,3, scope='conv1')
net = conv2d(net, 128,1, scope='conv2')
```
you will need to rewrite it to work with a learned parametrization (the json dict of learned sizes):
```
size_dict = {'conv1': 64, 'conv2': 128}
if parametrization_file:
  size_dict = ... # read dict from file. 
net = conv2d(inputs, size_dict['conv1'],3, scope='conv1')
net = conv2d(net, size_dict['conv2'], scope='conv2')
```
We plan to release a tool that provides this functionality soon.

**Comment by eladeban** [comment]
We released the `configurable_ops` module which should allow easy configuration of existing (and new networks).

Will be happy to hear if it works for you.

**Comment by AlanHuang1998** [comment]
Just want to ask, does any update of configurable_ops?

**Comment by AlanHuang1998** [comment]
If I use configurable_ops, does I need to add it before every net?
Can you show some sample? thanks a lot

**Comment by evi-Genius** [comment]
> If I use configurable_ops with trained model of morphnet, do I need to add it before every op, or just add once?
> Can you show the example? thanks a lot.
> Here is my part of the code below:
> `
> **inputs = ConfigurableOps(inputs)**
> inputs = conv2d_fixed_padding(
> inputs=inputs, filters=filters, kernel_size=3, strides=strides,
> data_format=data_format)
> inputs = batch_norm(inputs, training, data_format)
> inputs = tf.nn.relu(inputs)
> 
> inputs = conv2d_fixed_padding(
> inputs=inputs, filters=filters, kernel_size=3, strides=1,
> data_format=data_format)
> inputs = batch_norm(inputs, training, data_format)
> inputs += shortcut
> inputs = tf.nn.relu(inputs)
> 
> `

hello, dose this work?
