### ISSUE TITLE
Does MorphNet support object detection model, yolov3 or ssd?

### ISSUE THREAD

**Issue by herbiezhao** [google-research/morph-net#79]

**Comment by ouyangzhongqing** [comment]
if you verify successful in yolov3 or ssd?

**Comment by eladeban** [comment]
We don't have more results on these models. But targeting the backbone will work for sure (welcome to try, and if  you report back it will be great). Regarding the bounding boxes and so on, I think they also should work with GroupLasso regularizers but it is something you will need to figure out.

**Comment by spaul13** [comment]
@herbiezhao @ouyangzhongqing @eladeban can anyone please tell me how to apply morph-net on yolo models (while training using darknet (https://github.com/AlexeyAB/darknet))
