### ISSUE TITLE
Application to model including Keras upsampling layers (missing op handler)

### ISSUE THREAD

**Issue by lengerke** [google-research/morph-net#81]
I tried morphnet on my Keras-TF implementation of a skip network. Each deep module includes a Keras ```UpSampling2D``` layer, which upsamples a tensor from ```(batch_size, a, b, channels)``` to ```(batch_size, 2a, 2b, channels)```.  That's an issue because the tf ops ```ResizeNearestNeighbor``` and ```ResizeBilinear```, which are used by that layer, are not supported by morphnet at the moment. 

Before trying to implement the op handlers for these I quickly wanted to ask, whether the optimization routine might have inherent issues with upsamplings in general that might not be obvious at first.

Secondly, after reading #36 it is my understanding I could optimize a subnetwork between two upsampling layers by setting the input and output boundaries to these two layers respectively. Is that correct?

**Comment by eladeban** [comment]
Hi,

I might be missing something but I think nothing has to happen. From MorphNet's perspective, the `num_channels`, is not changing, so the default handling by the `grouping_op_handler` should work.

Please consider trying it, and if you get some error, we will be happy to help you debug it.

**Comment by eladeban** [comment]
@lengerke , let me know if it works, and if so you could close the issue.

**Comment by WAI-f** [comment]
> I tried morphnet on my Keras-TF implementation of a skip network. Each deep module includes a Keras `UpSampling2D` layer, which upsamples a tensor from `(batch_size, a, b, channels)` to `(batch_size, 2a, 2b, channels)`. That's an issue because the tf ops `ResizeNearestNeighbor` and `ResizeBilinear`, which are used by that layer, are not supported by morphnet at the moment.
> 
> Before trying to implement the op handlers for these I quickly wanted to ask, whether the optimization routine might have inherent issues with upsamplings in general that might not be obvious at first.
> 
> Secondly, after reading #36 it is my understanding I could optimize a subnetwork between two upsampling layers by setting the input and output boundaries to these two layers respectively. Is that correct?

Have you solve the upsampling problem?
